### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by henryiii** [ssciwr/clang-format-hook#4]
The author of pre-commit would prefer these sorts of repositories to be named with a `-hook` suffix, rather than `-precommit`, since it's not affiliated with pre-commit, and that's a common convention. See https://github.com/pre-commit/pre-commit.com/pull/564. I think everything will still work if it's renamed. Would renaming it be a good idea? The proposal would be `ssciwr/clang-format-hook`.

(Also avoids `pre-commit` vs. `precommit`)

**Comment by dokempf** [comment]
If that is @asottile's preference, I am fine with adopting it. I think that GitHub renaming automatically establishes URL forwarding so that the old URL will still work.
